import * as dependency_1 from "./../google/protobuf/any";
import * as dependency_2 from "./Link";
import * as pb_1 from "google-protobuf";
export declare class Waypoint extends pb_1.Message {
    #private;
    constructor(data?: any[] | {
        lat?: number;
        lon?: number;
        ele?: number;
        time?: number;
        magvar?: number;
        geoidheight?: number;
        name?: string;
        cmt?: string;
        desc?: string;
        src?: string;
        link?: dependency_2.Link[];
        sym?: string;
        type?: string;
        fix?: string;
        sat?: number;
        hdop?: number;
        vdop?: number;
        pdop?: number;
        ageofdgpsdata?: number;
        dgpsid?: number;
        extensions?: Map<string, dependency_1.google.protobuf.Any>;
    });
    get lat(): number;
    set lat(value: number);
    get lon(): number;
    set lon(value: number);
    get ele(): number;
    set ele(value: number);
    get time(): number;
    set time(value: number);
    get magvar(): number;
    set magvar(value: number);
    get geoidheight(): number;
    set geoidheight(value: number);
    get name(): string;
    set name(value: string);
    get cmt(): string;
    set cmt(value: string);
    get desc(): string;
    set desc(value: string);
    get src(): string;
    set src(value: string);
    get link(): dependency_2.Link[];
    set link(value: dependency_2.Link[]);
    get sym(): string;
    set sym(value: string);
    get type(): string;
    set type(value: string);
    get fix(): string;
    set fix(value: string);
    get sat(): number;
    set sat(value: number);
    get hdop(): number;
    set hdop(value: number);
    get vdop(): number;
    set vdop(value: number);
    get pdop(): number;
    set pdop(value: number);
    get ageofdgpsdata(): number;
    set ageofdgpsdata(value: number);
    get dgpsid(): number;
    set dgpsid(value: number);
    get extensions(): Map<string, dependency_1.google.protobuf.Any>;
    set extensions(value: Map<string, dependency_1.google.protobuf.Any>);
    static fromObject(data: {
        lat?: number;
        lon?: number;
        ele?: number;
        time?: number;
        magvar?: number;
        geoidheight?: number;
        name?: string;
        cmt?: string;
        desc?: string;
        src?: string;
        link?: ReturnType<typeof dependency_2.Link.prototype.toObject>[];
        sym?: string;
        type?: string;
        fix?: string;
        sat?: number;
        hdop?: number;
        vdop?: number;
        pdop?: number;
        ageofdgpsdata?: number;
        dgpsid?: number;
        extensions?: {
            [key: string]: ReturnType<typeof dependency_1.google.protobuf.Any.prototype.toObject>;
        };
    }): Waypoint;
    toObject(): {
        lat?: number | undefined;
        lon?: number | undefined;
        ele?: number | undefined;
        time?: number | undefined;
        magvar?: number | undefined;
        geoidheight?: number | undefined;
        name?: string | undefined;
        cmt?: string | undefined;
        desc?: string | undefined;
        src?: string | undefined;
        link?: {
            href?: string | undefined;
            text?: string | undefined;
            type?: string | undefined;
        }[] | undefined;
        sym?: string | undefined;
        type?: string | undefined;
        fix?: string | undefined;
        sat?: number | undefined;
        hdop?: number | undefined;
        vdop?: number | undefined;
        pdop?: number | undefined;
        ageofdgpsdata?: number | undefined;
        dgpsid?: number | undefined;
        extensions?: {
            [key: string]: {
                type_url?: string | undefined;
                value?: Uint8Array | undefined;
            };
        } | undefined;
    };
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Waypoint;
    serializeBinary(): Uint8Array;
    static deserializeBinary(bytes: Uint8Array): Waypoint;
}
//# sourceMappingURL=Waypoint.d.ts.map