/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.12.4
 * source: schemas/Link.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class Link extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        href?: string;
        text?: string;
        type?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("href" in data && data.href != undefined) {
                this.href = data.href;
            }
            if ("text" in data && data.text != undefined) {
                this.text = data.text;
            }
            if ("type" in data && data.type != undefined) {
                this.type = data.type;
            }
        }
    }
    get href() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set href(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get text() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set text(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get type() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set type(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        href?: string;
        text?: string;
        type?: string;
    }): Link {
        const message = new Link({});
        if (data.href != null) {
            message.href = data.href;
        }
        if (data.text != null) {
            message.text = data.text;
        }
        if (data.type != null) {
            message.type = data.type;
        }
        return message;
    }
    toObject() {
        const data: {
            href?: string;
            text?: string;
            type?: string;
        } = {};
        if (this.href != null) {
            data.href = this.href;
        }
        if (this.text != null) {
            data.text = this.text;
        }
        if (this.type != null) {
            data.type = this.type;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.href.length)
            writer.writeString(1, this.href);
        if (this.text.length)
            writer.writeString(2, this.text);
        if (this.type.length)
            writer.writeString(3, this.type);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Link {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Link();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.href = reader.readString();
                    break;
                case 2:
                    message.text = reader.readString();
                    break;
                case 3:
                    message.type = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Link {
        return Link.deserialize(bytes);
    }
}
